stages:
  - install
  - pack
  - quality

# This folder is cached between builds
default:
  cache:
    paths:
      - node_modules/
  before_script:
    - |
      {
        echo "@aqmo.org:registry=${CI_API_V4_URL}/projects/59/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/59/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc

install_media:
  stage: install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - nodejs
  variables:
    NODE_ENV: production
  script:
    - npm install

pack_media:
  stage: pack
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - nodejs
  variables:
    NODE_ENV: production
  script:
    - npm pack
  artifacts:
    name: "rudi_media.tgz"
    when: on_success
    paths:
      - ./rudi_media_drv-*.tgz

quality_lint:
  stage: quality
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
  tags:
    - nodejs
  variables:
    NODE_ENV: development
  script:
    - npm install
    - npm run lint
