stages:
  - npm_install
  - build
  - quality

# This folder is cached between builds
default:
  cache:
    paths:
    - node_modules/
    - front/node_modules/
  before_script:
    - |
      {
        echo "@aqmo.org:registry=${CI_API_V4_URL}/projects/59/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/59/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee -a .npmrc

# Front
front_npm:
  stage: npm_install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - nodejs
  variables:
    NODE_ENV: development
  script:
    - cd front && npm install

#
# Back
back_npm:
  stage: npm_install
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - nodejs
  variables:
    NODE_ENV: development
  script:
    - npm install

build_front:
  stage: build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - nodejs
  variables:
    NODE_ENV: development
    PUBLIC_URL: 68064ef1-1e5c-4384-8c50-626f52b78c5c
  script:
    - cd front && npm run build
  artifacts:
    name: 'ProdManager-front-$-PUBLIC_URL-rev$CI_COMMIT_SHORT_SHA'
    paths:
      - front/build/
    expire_in: 10 week

# Global
lint:
  stage: quality
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - nodejs
  script:
    - npm run lint
