# https://github.com/grafana/loki/blob/main/docs/sources/clients/promtail/configuration.md

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.42.22.179:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'


  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:514
      idle_timeout: 60s
      label_structured_data: yes
      labels:
        job: "syslog"
    relabel_configs:
      - source_labels: ['__syslog_connection_ip_address']
        target_label: 'ip'
      - source_labels: ['__syslog_connection_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_severity']
        target_label: 'severity'
      - source_labels: ['__syslog_message_facility']
        target_label: 'facility'
      - source_labels: ['__syslog_message_hostname']
        target_label: 'source'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'appname'
      - source_labels: ['__syslog_message_proc_id']
        target_label: 'procid'
      - source_labels: ['__syslog_message_msg_id']
        target_label: 'msgid'

        #  - job_name: filesystem
        #    pipeline_stages:
        #    static_configs:
        #    - labels:
        #          job: "varlogs"
        #          host: rudihome
        #          __path__: /var/log/*.log
